### ISSUE TITLE
Adaptive border radius not working in Firefox

### ISSUE THREAD

**Issue by dougmacknz** [discord/focus-rings#7]
See forked example with more exaggerated border radius: https://codesandbox.io/s/hidden-cloud-o8vrl

![image](https://user-images.githubusercontent.com/1811583/121103608-a1550600-c843-11eb-9a9c-021f081ff5c8.png)

Working fine in Chrome and Safari:
![image](https://user-images.githubusercontent.com/1811583/121104317-1c6aec00-c845-11eb-924a-fc4f2d9da0cc.png)

**Comment by faultyserver** [comment]
Interesting! It looks like Firefox doesn't return `borderRadius` in at all the same way that webkit browsers do:

Firefox:
![image](https://user-images.githubusercontent.com/783733/122603747-d4b54300-d042-11eb-987b-225e530bdd2c.png)
Chrome:
![image](https://user-images.githubusercontent.com/783733/122603950-31b0f900-d043-11eb-811b-46125b910d76.png)

I'm not sure _why_ Firefox isn't populating the regular `borderRadius` property, but that is what we rely on to [calculate the adaptive border radius](https://github.com/discord/focus-rings/blob/a0ca56d7286c5b54cdf4e200ddb944be4564e52d/src/FocusRingContext.tsx#L108), so that's why it's not adapting there at least.

Since the inividual corner values _are_ populated, maybe we can do something with that and build up the value from the corners to be more flexible?
